version: '3.1'
services:
  redis1:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16379:6379
  redis2:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16380:6379
  redis3:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16381:6379
  redis4:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16382:6379
